### ISSUE TITLE
Some internal references need to be fixed

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/aplus-manual#23]
In some cases, the references make use of full URLs that point to the localhost. These types of references cause hyperlinks to point to the http://www.localhost:8000/def/current/, which is not the desired behaviour.
![image](https://user-images.githubusercontent.com/10437475/87977040-b95e5280-cad6-11ea-91eb-251393d417e6.png)

Some other references implement relative URLs and point to the old name of the course folders, which included a numerical value at the beginning. These references need to be updated.
![image](https://user-images.githubusercontent.com/10437475/87976947-992e9380-cad6-11ea-9419-3dc1a7189722.png)
![image](https://user-images.githubusercontent.com/10437475/87977003-a9df0980-cad6-11ea-898f-c67ad89f146a.png)

**Comment by markkuriekkinen** [comment]
Chapter links should be given as relative paths in the RST (e.g., `<../m02_programming_exercises/06_radar>`. The link should then work correctly both in the localhost and in the server.

**Comment by jaguarfi** [comment]
It seems that those links are actually pointing to the grader.cs.hut.fi server. Is that the expected behaviour? 
![image](https://user-images.githubusercontent.com/10437475/90651809-24ba5200-e246-11ea-87f1-2e78f7216a6b.png)

And as a result, the link takes you to the grader.
![image](https://user-images.githubusercontent.com/10437475/90651947-4a475b80-e246-11ea-8dfe-53eb953a065f.png)

**Comment by markkuriekkinen** [comment]
Remember that Sphinx compiles RST first and local links are usually relative file paths in the compiled HTML files under the `_build` directory. However, when A+ renders the chapter, it modifies links so that chapter links work inside A+ (chapter links must point to A+ of course). If chapter links refer to the MOOC-Grader server, then they are broken, but the problem usually originates from the RST compilation. A+ expects a certain form from those links. There have been many bugs with special cases and nesting directories under the module directory in the course source code has also caused problems.

* a-plus-rst-tools has some hacky code for modifying chapter and static links so that A+ could fix when they are rendered in A+: https://github.com/apluslms/a-plus-rst-tools/blob/master/lib/html_tools.py
* https://github.com/apluslms/a-plus/blob/master/exercise/protocol/aplus.py
* https://github.com/apluslms/a-plus/blob/master/lib/remote_page.py#L161

**Comment by jaguarfi** [comment]
Interesting behaviour. However, I think that the `:ref:` and `:doc:` roles work quite good and are suggested in the [Sphinx documentation](https://www.sphinx-doc.org/en/1.7/markup/inline.html#cross-referencing-arbitrary-locations) for referencing other parts of the course. So we can try to use those links as well and see how they behave.

And yes, the relative paths may be working properly. However, the current behaviour in the [A+ manual](https://plus.cs.aalto.fi/aplus-manual/master/) is that a couple of links are trying to read information from https://grader.cs.hut.fi. In any case, I think that behaviour is due to those references using relative paths are trying to find a folder that no longer exists (These folder names were changed in #16)

**Comment by raphendyr** [comment]
If there is no `'data-aplus-chapter`, then A+ most likely doesn't handle the link correctly. I think that is an area that should be looked at. We have a lot of requirements from the assessment service for the A+ to work, when A+ should be fine without any special things. I think I had some issues to write about this to A+ repo.

**Comment by markkuriekkinen** [comment]
> Interesting behaviour. However, I think that the `:ref:` and `:doc:` roles work quite good and are suggested in the [Sphinx documentation](https://www.sphinx-doc.org/en/1.7/markup/inline.html#cross-referencing-arbitrary-locations) for referencing other parts of the course. So we can try to use those links as well and see how they behave.
> 
> And yes, the relative paths may be working properly. However, the current behaviour in the [A+ manual](https://plus.cs.aalto.fi/aplus-manual/master/) is that a couple of links are trying to read information from https://grader.cs.hut.fi. In any case, I think that behaviour is due to those references using relative paths are trying to find a folder that no longer exists (These folder names were changed in #16)

I would confirm that some links were probably broken simply because the relative path was incorrect after the directories had been renamed. The problem then escalates further and a-plus-rst-tools and a-plus can not fix the link, thus the link ends up pointing to the grader backend.
